  POST http://localhost:5203/api/transactions
  Content-Type: application/json                                                
                  
  {                                                                             
    "amount": 100.00,
    "currency": "BRL",
    "description": "Almoço",
    "type": "Expense",
    "categoryId": "3fa85f64-5717-4562-b3fc-2c963f66afa6"                        
  }

###
    GET http://localhost:5203/api/transactions/78159ec7-7650-4408-8a25-fc61038857eb
    Content-Type: application/json


### Get all transactions
    GET http://localhost:5203/api/transactions
    Content-Type: application/json